# Generated by Django 4.2.1 on 2025-02-12 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0002_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapper_count', models.IntegerField()),
                ('pack_count', models.IntegerField()),
                ('deck_card_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card1', to='backend.card')),
                ('deck_card_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card2', to='backend.card')),
                ('deck_card_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card3', to='backend.card')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
