# Generated by Django 4.2.1 on 2025-02-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='team_id',
            new_name='team_name',
        ),
    ]
