# Generated by Django 4.2.1 on 2025-02-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_gym_radius'),
        ('accounts', '0003_alter_profile_deck_card_1_alter_profile_deck_card_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deck_card_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card1', to='backend.playercards'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deck_card_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card2', to='backend.playercards'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deck_card_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card3', to='backend.playercards'),
        ),
    ]
