# Generated by Django 4.2.1 on 2025-02-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_profile'),
        ('accounts', '0002_rename_team_id_profile_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='deck_card_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card1', to='backend.card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deck_card_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card2', to='backend.card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deck_card_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card3', to='backend.card'),
        ),
    ]
