# Generated by Django 5.1.6 on 2025-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_alter_profile_deck_card_1_alter_profile_deck_card_2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="battles_won",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="bins_emptied",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="packs_opened",
            field=models.IntegerField(default=0),
        ),
    ]
