# Generated by Django 5.1.6 on 2025-03-05 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_battles_won_profile_bins_emptied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_pack_allocation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
