# Generated by Django 5.1.6 on 2025-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_card_ability_self_power_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="fact",
            field=models.CharField(max_length=200),
        ),
    ]
