# Generated by Django 4.2.1 on 2025-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(upload_to='static/images/achievement/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.ImageField(upload_to='static/images/teams/'),
        ),
    ]
