# Generated by Django 4.2.1 on 2025-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_achievement_icon_alter_team_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user_selectable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
