# Generated by Django 5.1.6 on 2025-03-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_achievement_icon_alter_card_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerachievements",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="date_unlocked",
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="battles_won_10",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="battles_won_25",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="battles_won_50",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="bins_emptied_10",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="bins_emptied_25",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="bins_emptied_50",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="packs_opened_10",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="packs_opened_25",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="packs_opened_50",
            field=models.BooleanField(default=False),
        ),
    ]
