# Generated by Django 5.1.6 on 2025-03-04 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_remove_playerachievements_achievement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerachievements",
            name="battles_won_10",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="battles_won_25",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="battles_won_50",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="bins_emptied_10",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="bins_emptied_25",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="bins_emptied_50",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="packs_opened_10",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="packs_opened_25",
        ),
        migrations.RemoveField(
            model_name="playerachievements",
            name="packs_opened_50",
        ),
        migrations.AddField(
            model_name="achievement",
            name="threshold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="achievement",
            name="type",
            field=models.CharField(
                choices=[
                    ("PACKS", "Packs Opened"),
                    ("BATTLES", "Battles Won"),
                    ("BINS", "Bins Emptied"),
                ],
                default="PACKS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="achievement",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.achievement",
            ),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="date_achieved",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="playerachievements",
            name="pack_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.ImageField(upload_to="achievements/"),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="tier",
            field=models.IntegerField(default=1),
        ),
    ]
