# Generated by Django 5.1.6 on 2025-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_remove_playerachievements_battles_won_10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="icon",
            field=models.CharField(
                choices=[
                    ("static/images/backend/profile/bronzemedal.png", "Bronze"),
                    ("static/images/backend/profile/silvermedal.png", "Silver"),
                    ("static/images/backend/profile/goldmedal.png", "Gold"),
                ],
                default="achievements/bronze.png",
                max_length=255,
            ),
        ),
    ]
