# Generated by Django 4.2.1 on 2025-02-11 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tier', models.IntegerField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('card_type', models.IntegerField()),
                ('ability_name_1', models.CharField(max_length=100)),
                ('ability_power_1', models.IntegerField()),
                ('ability_name_2', models.CharField(max_length=100)),
                ('ability_power_2', models.IntegerField()),
                ('health_points', models.IntegerField()),
                ('fact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapper_count', models.IntegerField()),
                ('pack_count', models.IntegerField()),
                ('deck_card_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card1', to='backend.card')),
                ('deck_card_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card2', to='backend.card')),
                ('deck_card_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_deck_card3', to='backend.card')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_gym', models.BooleanField()),
                ('use_count', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_unlocked', models.DateTimeField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fact', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cooldown', models.DateTimeField()),
                ('card1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_card1', to='backend.card')),
                ('card2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_card2', to='backend.card')),
                ('card3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_card3', to='backend.card')),
                ('owning_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
