# Generated by Django 4.2.1 on 2025-02-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_achievement_icon_alter_team_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='radius',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
