name: Django CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Dependencies
              run: |
                  cd technical-documents/source-code
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run Migrations and Tests
              env:
                  DJANGO_SETTINGS_MODULE: ecomon.settings
              run: |
                  cd ecomon
                  python manage.py migrate
                  python manage.py test
